# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fest
    main: ./cmd/fest
    binary: fest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: fest
    name_template: >-
      fest_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: anthropics
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    name: fest

    homepage: "https://github.com/anthropics/guild-framework"
    description: "Festival methodology CLI for managing software development festivals"
    license: "MIT"

    folder: Formula

    test: |
      system "#{bin}/fest", "--version"

    install: |
      bin.install "fest"

release:
  github:
    owner: anthropics
    name: guild-framework

  prerelease: auto

  header: |
    ## fest {{ .Tag }}

    Festival methodology CLI release

  footer: |
    **Full Changelog**: https://github.com/anthropics/guild-framework/compare/{{ .PreviousTag }}...{{ .Tag }}

# Universal binaries for macOS
universal_binaries:
  - replace: true
    id: fest
    name_template: "fest"