#!/usr/bin/env just --justfile
# fest CLI build and development tasks

# Module imports
mod build '.justfiles/build.just'
mod test '.justfiles/test.just'
mod release '.justfiles/release.just'
mod quality '.justfiles/quality.just'
mod install '.justfiles/install.just'
mod run '.justfiles/run.just'

# Show available commands (default)
[private]
@default:
    @just --list --unsorted

# Run all tests and build
all:
    just test test
    just build build
